//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurux.DLT645.AddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gurux.DLT645.AddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector Address.
        /// </summary>
        internal static string CollectorAddressTxt {
            get {
                return ResourceManager.GetString("CollectorAddressTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data ID.
        /// </summary>
        internal static string DataIDTxt {
            get {
                return ResourceManager.GetString("DataIDTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DLTItems&gt;
        ///  &lt;!--Access modes 1=Read, 2=Write 3=ReadWrite. Default value is 1.--&gt;
        ///  &lt;Properties&gt;
        ///    &lt;Property ID=&quot;00010000&quot; Name=&quot;Current active total energy&quot; Type=&quot;UInt32&quot; /&gt;
        ///    &lt;Property ID=&quot;00010100&quot; Name=&quot;Current active energy(T1)&quot; Type=&quot;UInt32&quot; /&gt;
        ///    &lt;Property ID=&quot;00010200&quot; Name=&quot;Current active energy(T2)&quot; Type=&quot;UInt32&quot; /&gt;
        ///    &lt;Property ID=&quot;00010300&quot; Name=&quot;Current active energy(T3)&quot; Type=&quot;UInt32&quot; /&gt;
        ///    &lt;Property ID=&quot;00010400&quot; Name=&quot;Current active energy(T4)&quot; Type=&quot;UInt32&quot; /&gt;
        ///    &lt;Property I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DLTProperties {
            get {
                return ResourceManager.GetString("DLTProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Leading Bytes.
        /// </summary>
        internal static string FrontLeadingBytesTxt {
            get {
                return ResourceManager.GetString("FrontLeadingBytesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Class Password.
        /// </summary>
        internal static string LowClassPasswordTxt {
            get {
                return ResourceManager.GetString("LowClassPasswordTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Address.
        /// </summary>
        internal static string MeterAddressTxt {
            get {
                return ResourceManager.GetString("MeterAddressTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Information.
        /// </summary>
        internal static string MeterInformationTxt {
            get {
                return ResourceManager.GetString("MeterInformationTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Password.
        /// </summary>
        internal static string MeterPasswordTxt {
            get {
                return ResourceManager.GetString("MeterPasswordTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Code.
        /// </summary>
        internal static string OperatorCodeTxt {
            get {
                return ResourceManager.GetString("OperatorCodeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay Control Password.
        /// </summary>
        internal static string RelayControlPasswordTxt {
            get {
                return ResourceManager.GetString("RelayControlPasswordTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeTxt {
            get {
                return ResourceManager.GetString("TypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set meter address.
        /// </summary>
        internal static string UpdateMeterAddressTxt {
            get {
                return ResourceManager.GetString("UpdateMeterAddressTxt", resourceCulture);
            }
        }
    }
}
